Camera Tracker: GenericCamera::disconnected_exception Class Reference
GenericCamera::disconnected_exception Class Reference
Exception if device is is disconnected Exception specificly for device disconnection, inherits from std exeception.
#include <GenericCamera.h>
Public Member Functions
disconnected_exception ()
Detailed Description
Exception if device is is disconnected Exception specificly for device disconnection, inherits from std exeception.
Constructor & Destructor Documentation
disconnected_exception()
GenericCamera::disconnected_exception::disconnected_exception () inline
constructor, calling the std exception construction
Parameters
[in] description descriptive error text
References GenericCamera::detach(), GenericCamera::GenericCamera(), GenericCamera::getExposure(), GenericCamera::getFrame(), GenericCamera::initialize(), GenericCamera::setExposure(), GenericCamera::setExposureMode(), and GenericCamera::~GenericCamera().
The documentation for this class was generated from the following file:
/home/bdn_jz/bdn_jz/CameraTrackerLinux/include/GenericCamera.h