Camera Tracker: BaslerGigECamera Class Reference
BaslerGigECamera Class Reference
Implementation of Basler GigE Cameras.
#include <BaslerGigECamera.h>
Public Member Functions
BaslerGigECamera ()
~BaslerGigECamera ()
bool initialize (const std::string id) override
bool reset ()
void detach (void) override
cv::Mat getFrame (void) override
bool setExposureMode (ExposureModes mode) override
bool setExposure (const double time) override
double getExposure (void) const override
void loadFeatureFile (const std::string filename) override
Public Member Functions inherited from GenericCamera
GenericCamera ()
virtual ~GenericCamera ()
ExposureModes getExposureMode (void) const
ExposureStates getExposureState (void) const
virtual bool laserExposure (cv::Mat &image)
const std::string getName (void) const
void setPitch (double newPitch)
const double getPitch (void) const
Static Public Member Functions
static std::vector< std::string > listAvailableDevices (void)
Additional Inherited Members
Protected Attributes inherited from GenericCamera
std::string name
device identifier
double exposureStep
smallest step between two exposure times
ExposureModes exposureMode
current exposure mode set
double pitch
ratio of millimeter per pixel
ExposureStates exposureState
current state of the exposure
Detailed Description
Implementation of Basler GigE Cameras.
Class that wraps the Basler Pylon controls for GigE Camera to the generic camera controls used in the software and implements the image acquisistion
Constructor & Destructor Documentation
BaslerGigECamera()
BaslerGigECamera::BaslerGigECamera ()
constructor, takes no arguments
References BASLER_DEFAULT_PITCH, and GenericCamera::pitch.
~BaslerGigECamera()
BaslerGigECamera::~BaslerGigECamera ()
destructor
Member Function Documentation
detach()
void BaslerGigECamera::detach (void) override virtual
close the attached pylon device
Implements GenericCamera.
Referenced by initialize(), and reset().
getExposure()
double BaslerGigECamera::getExposure (void) const override virtual
get the current exposure time
Returns
current exposure time in milliseconds
Implements GenericCamera.
getFrame()
cv::Mat BaslerGigECamera::getFrame (void) override virtual
get a single frame from the camera and convert it to an openCV matrix
Returns
acquired frame in openCV matrix format.
Implements GenericCamera.
References GenericCamera::exposureMode.
initialize()
bool BaslerGigECamera::initialize (const std::string id) override virtual
initialize the choosen device, passing the name from the list as string
Parameters
[in] id name of the device to start
Returns
success of initialization progress, i.e. if the camera could be activated
Implements GenericCamera.
References detach(), GenericCamera::exposureStep, and GenericCamera::name.
Referenced by reset().
listAvailableDevices()
std::vector< std::string > BaslerGigECamera::listAvailableDevices (void) static
static function that lists all available cameras on the network
Returns
standard vector with device names as string
loadFeatureFile()
void BaslerGigECamera::loadFeatureFile (const std::string filename) override virtual
load a basler specific feature file, containing settings stored with the Pylon Viewer application, to the device
Parameters
[in] filename filename of the feature file
Implements GenericCamera.
reset()
bool BaslerGigECamera::reset ()
reset the choosen device, i.e. first detach and then initialize it
Returns
success of initialization progress, i.e. if the camera could be activated
References detach(), and initialize().
setExposure()
bool BaslerGigECamera::setExposure (const double time) override virtual
manually set the exposure time of the camera, only works if the mode is not automatic
Parameters
[in] time exposure time in milliseconds
Returns
true if exposure time vcould be written to the device, false else
Implements GenericCamera.
setExposureMode()
bool BaslerGigECamera::setExposureMode (ExposureModes mode) override virtual
set the exposure mode of the camera, choosing between automatic, manual and laser
Parameters
[in] mode desired exposure setting
Returns
true if exposure mode could be set, false else
Implements GenericCamera.
References GenericCamera::setExposureMode().
The documentation for this class was generated from the following files:
/home/bdn_jz/bdn_jz/CameraTrackerLinux/include/BaslerGigECamera.h
/home/bdn_jz/bdn_jz/CameraTrackerLinux/src/BaslerGigECamera.cpp