Camera Tracker: CodeScanner Class Reference
CodeScanner Class Reference
Class that contains the precedures of finding the position of code and decoding the code.
#include <Scanner.h>
Public Member Functions
CodeScanner ()
Constructor of CodeScanner class.
~CodeScanner ()
Deconstructor of CodeScanner class.
CodeInfo getCodeInfo (ChessboardDetectorResult detection, float findOriginX, float findOriginY, float findEndX, float findEndY)
Function that estimates the coordinates of code's corners based on the upper left corner of the chessboard.
CodeInfo decode (ChessboardDetectorResult detection, CodeInfo codeInfo, const std::string &name)
Function that decodes the code to get the type and data.
Public Attributes
CodeInfo codeInfo
Detailed Description
Class that contains the precedures of finding the position of code and decoding the code.
Member Function Documentation
decode()
CodeInfo CodeScanner::decode (ChessboardDetectorResult detection, CodeInfo codeInfo, const std::string & name)
Function that decodes the code to get the type and data.
Parameters
detection Result of chessboard detection.
codeInfo Related information about the code.
name Name of the code. (Only used for displaying the code)
Returns
A structure of the complete information about the code
References ChessboardDetectorResult::perspective.
Referenced by BarcodeScanner::BarcodeScanner(), and QrcodeScanner::QrcodeScanner().
getCodeInfo()
CodeInfo CodeScanner::getCodeInfo (ChessboardDetectorResult detection, float findOriginX, float findOriginY, float findEndX, float findEndY)
Function that estimates the coordinates of code's corners based on the upper left corner of the chessboard.
Parameters
detection Result of chessboard detection.
findOriginX X-coordinate of the down left corner of the code.
findOriginY Y-coordinate of the down left corner of the code.
findEndX X-coordinate of the up right corner of the code.
findEndY Y-coordinate of the up right corner of the code.
Returns
A structure of the partial information about the code
References ChessboardDetectorResult::boundingRectangle, ChessboardDetectorResult::perspectiveCopy, ChessboardDetectorResult::unitHeight, and ChessboardDetectorResult::unitWidth.
Referenced by BarcodeScanner::BarcodeScanner(), and QrcodeScanner::QrcodeScanner().
The documentation for this class was generated from the following files:
/home/bdn_jz/bdn_jz/CameraTrackerLinux/include/Scanner.h
/home/bdn_jz/bdn_jz/CameraTrackerLinux/src/Scanner.cpp