Camera Tracker: ChessboardDetector Class Reference
ChessboardDetector Class Reference
Implementation of chessboard detection.
#include <ChessboardDetector.h>
Public Member Functions
ChessboardDetector (Chessboard chessboard, cv::Mat sourceImage)
Constructor that performs the whole procedure to get the chessboard detection result.
~ChessboardDetector ()
Deconstructor of ChessboardDetector class.
FindCornersResult findChessboardCorners (cv::Mat image, Chessboard chessboard)
Function that finds the corners in the original image.
PerspectiveResult perspectiveChessboard (FindCornersResult corners)
Functions that contains the whole procedure of perspective transformation.
ChessboardDetectorResult detectionResult (cv::Mat originalImage, Chessboard chessboard)
Functions that returns the result of chessboard detection.
ChessboardDetectorResult getResult ()
Function used to get the detection result outside the class.
FindCornersResult getOriginalCorners ()
Function that finds the corners in the original image.
cv::Mat preprocess (cv::Mat originalImage)
Function that resize the image so that the longest side has 860 pixels.
Detailed Description
Implementation of chessboard detection.
This class wraps the preprocessing of a image and the detection of the chessboard in the image.
Constructor & Destructor Documentation
ChessboardDetector()
ChessboardDetector::ChessboardDetector (Chessboard chessboard, cv::Mat sourceImage)
Constructor that performs the whole procedure to get the chessboard detection result.
Parameters
chessboard Chessboard to detect.
sourceImage Input image.
References detectionResult().
Member Function Documentation
detectionResult()
ChessboardDetectorResult ChessboardDetector::detectionResult (cv::Mat originalImage, Chessboard chessboard)
Functions that returns the result of chessboard detection.
Parameters
originalImage Input image without any preprocessing.
chessboard Configuration of the chessboard.
Returns
Structured data of ChessboardDetectorResult.
References PerspectiveResult::boundingBox, ChessboardDetectorResult::boundingBox, PerspectiveResult::boundingRectangle, ChessboardDetectorResult::boundingRectangle, FindCornersResult::corners, ChessboardDetectorResult::corners, findChessboardCorners(), Chessboard::getHeight(), Chessboard::getWidth(), PerspectiveResult::image, ChessboardDetectorResult::image, PerspectiveResult::perspective, ChessboardDetectorResult::perspective, perspectiveChessboard(), ChessboardDetectorResult::perspectiveCopy, ChessboardDetectorResult::scale, FindCornersResult::success, ChessboardDetectorResult::success, ChessboardDetectorResult::unitHeight, and ChessboardDetectorResult::unitWidth.
Referenced by ChessboardDetector().
findChessboardCorners()
FindCornersResult ChessboardDetector::findChessboardCorners (cv::Mat image, Chessboard chessboard)
Function that finds the corners in the original image.
Parameters
image Input image.
chessboard Configuration of the chessboard.
Returns
Structured data of FindCornersResult.
References FindCornersResult::corners, Chessboard::getHeight(), Chessboard::getWidth(), FindCornersResult::image, preprocess(), and FindCornersResult::success.
Referenced by detectionResult().
getOriginalCorners()
FindCornersResult ChessboardDetector::getOriginalCorners ()
Function that finds the corners in the original image.
Returns
structure of FindCornersResult.
getResult()
ChessboardDetectorResult ChessboardDetector::getResult ()
Function used to get the detection result outside the class.
Returns
structure of ChessboardDetectorResult.
perspectiveChessboard()
PerspectiveResult ChessboardDetector::perspectiveChessboard (FindCornersResult corners)
Functions that contains the whole procedure of perspective transformation.
Parameters
corners Result of finding corners in the image.
Returns
Structured data of PerspectiveResult.
References PerspectiveResult::boundingBox, PerspectiveResult::boundingRectangle, FindCornersResult::corners, FindCornersResult::image, PerspectiveResult::image, and PerspectiveResult::perspective.
Referenced by detectionResult().
preprocess()
cv::Mat ChessboardDetector::preprocess (cv::Mat originalImage)
Function that resize the image so that the longest side has 860 pixels.
Parameters
originalimage Input image for preprocessing.
Returns
a matrix containing all the intensity values of the pixel points.
Referenced by findChessboardCorners().
The documentation for this class was generated from the following files:
/home/bdn_jz/bdn_jz/CameraTrackerLinux/include/ChessboardDetector.h
/home/bdn_jz/bdn_jz/CameraTrackerLinux/src/ChessboardDetector.cpp